import os.path
import random

import yaml

from src.map_objects import *
from src.res.Important import max_x, max_y, enemy_keys


class Objects:
    def __init__(self):
        self.lists = {'Monster': [], 'Orc': [], 'Troll': [],
                      'Gold': [], 'Wall': [], 'Food': [], 'Map item': [],
                      'StairsUp': [], 'StairsDown': [],
                      'Hero': []
                      }
        # Define create and add mandatory objects.
        self.lists.get('StairsUp').append(StairsUp(1, 1))
        self.lists.get('StairsDown').append(StairsDown(max_x, max_y))
        self.lists.get('Hero').append(Hero(int(max_x / 2), int(max_y / 2), 'Ja', '1'))
        self.lists.get('Hero').append(Hero(int(max_x / 2) + 1, int(max_y / 2), 'Ty', '2'))
        self.lists.get('Hero').append(Hero(int(max_x / 2), int(max_y / 2) + 1, 'On', '3'))

        absolute_path = os.path.abspath(os.path.dirname(__file__))
        items_path = os.path.join(absolute_path, 'res/Items.yml')
        with open(items_path, 'r') as file:
            self.item_keys = list(yaml.load(file).keys())

    def check_limit(self):
        object_count = 0
        for i in self.lists.keys():
            object_count = object_count + len(self.lists.get(i))

        object_limit = max_x * max_y

        if (object_count >= object_limit):
            return True
        return False

    def check_coords(self, new_x, new_y):
        """verify if coords of object to be created are not in use"""

        for i in self.lists.keys():
            for j in self.lists.get(i):
                if (new_x == j.x and new_y == j.y):
                    return True

        return False

    def get_object(self, x, y, blacklist=None):
        """
        returns object at given coords or None if empty
        blacklist allows ignoring some objects (type_name)
        """
        for i in self.lists.keys():
            for j in self.lists.get(i):
                if (j.x == x and j.y == y and j.type_name != blacklist):
                    return j
        return None

    def create_object(self, object_type, x, y):
        """
        Objects that are created multiple times at random.
        If object_type does not match any of expected types, no object is created
        More strictly defined objects are mostly generated by direct sppending

        :param object_type: type of added object
        :param x: horizontal map coordinate
        :param y: vertical map coordinate
        :return: returns nothing
        """
        if (object_type == 'Monster'):
            self.lists.get(object_type).append(Monster(x, y))
        elif (object_type == 'Gold'):
            self.lists.get(object_type).append(Gold(x, y))
        elif (object_type == 'Wall'):
            self.lists.get(object_type).append(Wall(x, y))
        elif (object_type == 'Food'):
            self.lists.get(object_type).append(Food(x, y))
        elif (object_type == 'Map item'):
            new_id = self.item_keys[random.randint(0, len(self.item_keys) - 1)]
            self.lists.get(object_type).append(MapItem(new_id, x, y))

    def remove_object(self, removed_object):
        """removes given object"""
        x = removed_object.x
        y = removed_object.y
        for i in self.lists.keys():
            for j in self.lists.get(i):
                if (j.x == x and j.y == y):
                    if j.type_name == 'Hero':
                        j.status = 'dead'
                        j.mark = '+'
                        return 0
                    self.lists.get(i).remove(j)
                    return 0
        return 1

    def count(self):
        result = 0
        for i in self.lists.keys():
            for j in self.lists.get(i):
                result += 1
        return result

    def count_enemies(self):
        result = 0
        for i in enemy_keys:
            for j in self.lists.get(i):
                result += 1
        return result

    def hello(self, stdscr):
        y = 5
        for i in self.lists.keys():
            for j in self.lists.get(i):
                j.hello(stdscr, y)
                y += 1

    def hello2(self, stdscr):
        y = 5
        for i in range(max_x):
            for j in range(max_y):
                k = self.get_object(i, j)
                if (k is not None):
                    k.hello(stdscr, y)
                    y += 1
                j += 1
            i += 1
